# Generated by Django 2.1 on 2018-11-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('CONTENT', models.TextField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
